# Generated by Django 5.0.3 on 2024-03-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartproduct',
            unique_together={('product',)},
        ),
    ]
