# Generated by Django 5.0.3 on 2025-02-15 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cartproduct_unique_together_and_more'),
        ('products', '0002_alter_productvariant_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favorite',
            name='product_variant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'product_variant')},
        ),
    ]
